spring.application.name=auction-system
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.datasource.url=jdbc:h2:mem:auctionSystem;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===== Thymeleaf =====
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ===== Error pages =====
server.error.include-message=always
server.error.include-binding-errors=always

# ===== Logging =====
logging.level.pl.auction_system=INFO
